<?php


/**
 * Implements hook_field_formatter_info()
 */

function fb_field_formatter_info() {
  return array(
    'fb_formatter' => array(
      'label' => t('Facebook Link'),
      'field types' => array('text', 'text_long', 'text_with_summary'),
      'settings' => array(
        'pic_size' => 'small',
        'tooltip' => 'Link to user Facebook page',
        ),
      ),
  );
}

function fb_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  //This gets the view_mode where our settings are stored
  $display = $instance['display'][$view_mode];
  //Actual settings
  $settings = $display['settings'];
  //Init the element variable
  $element = array();
  $element['pic_size'] = array (
    '#type'             => 'select',
    '#title'            => t('Button size'),
    '#description'      => t('Select what size of FB BUtton'),
    '#default_value'    => $settings['fb_size'],
    '#options'          => array(
      'small' => 'Small',
      'medium' => 'Medium',
      'large' => 'Large',
      ),
    );
  $element['tooltip'] = array(
    '#type'   => 'textfield',
    '#title'  => t('Tooltip'),
    '#description' => t('This text will appear when a user mouseover'),
    '#default_value' => $settings['tooltip'],
  );
  return $element;
}

function fb_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('Use a @size Facebook button with the tooltip of "@tooltip"', array(
    '@size'    => $settings['pic_size'],
    '@tooltip' => $settings['tooltip'],
  ));
  return $summary;
}

function fb_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];
  $size = $settings['pic_size'];
  $tooltip = $settings['tooltip'];
  $image = '<img src= "/' .drupal_get_path('module', 'fb'). '/images/' .$size. '.png">';
  $settext = '<h1> </h1>';

  foreach($items as $delta => $item) {
    $fb1 = $item['safe_value']; //Getting the actual value
  }
  $options = array(
    'html' => TRUE,
    'attributes' => array(
      'title' => $tooltip,
    ),
  );

  if(isset($fb1)) {
    $link = l($image, $fb1, $options); //Create a link
    $element[0]['#markup'] = $link; //Assign it to the markup 
  }

  return $element;

}